# Generated by Django 5.1.3 on 2024-12-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_bessie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_health', models.FloatField()),
                ('mental_health', models.FloatField()),
                ('self_care', models.FloatField()),
                ('emotional_health', models.FloatField()),
                ('emotional_distress', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResultComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_health', models.TextField()),
                ('mental_health', models.TextField()),
                ('self_care', models.TextField()),
                ('emotional_health', models.TextField()),
                ('emotional_distress', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_bessie.quizresult')),
            ],
        ),
    ]
