# Generated by Django 5.1.3 on 2025-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='teams',
            field=models.JSONField(default=list),
        ),
    ]
