# Generated by Django 5.1.3 on 2025-02-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0004_company_induction_video_company_results_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bessieresult',
            name='potential_cost',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
    ]
