# Generated by Django 5.1.3 on 2025-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0005_bessieresult_potential_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bessieresponse',
            name='idNumber',
        ),
        migrations.AlterField(
            model_name='company',
            name='induction_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='results_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
