# Generated by Django 5.1.3 on 2025-03-03 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0006_remove_bessieresponse_idnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='strategy_meeting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='survey_completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='survey_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
