# Generated by Django 5.1.3 on 2025-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0007_company_strategy_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='teams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
