# Generated by Django 5.1.3 on 2025-03-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0008_alter_company_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
