# Generated by Django 5.1.3 on 2025-04-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0011_company_results_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRiskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_and_wellbeing_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('veryhigh', 'Very High')], default='low', max_length=10)),
                ('stress_and_wellbeing_in_place', models.TextField()),
                ('stress_and_wellbeing_recommendations', models.TextField()),
                ('stress_and_wellbeing_risk_date', models.DateField()),
                ('workplace_stress_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('veryhigh', 'Very High')], default='low', max_length=10)),
                ('workplace_stress_in_place', models.TextField()),
                ('workplace_stress_recommendations', models.TextField()),
                ('workplace_stress_risk_date', models.DateField()),
                ('presenteeism_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('veryhigh', 'Very High')], default='low', max_length=10)),
                ('presenteeism_in_place', models.TextField()),
                ('presenteeism_recommendations', models.TextField()),
                ('presenteeism_risk_date', models.DateField()),
                ('wider_risks_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('veryhigh', 'Very High')], default='low', max_length=10)),
                ('wider_risks_in_place', models.TextField()),
                ('wider_risks_recommendations', models.TextField()),
                ('wider_risks_risk_date', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bessie.company')),
            ],
        ),
    ]
