# Generated by Django 5.1.3 on 2025-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bessie', '0012_companyrisksummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrisksummary',
            name='presenteeism_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyrisksummary',
            name='stress_and_wellbeing_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyrisksummary',
            name='wider_risks_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyrisksummary',
            name='workplace_stress_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
