# Generated by Django 5.1.3 on 2025-04-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bessie", "0013_alter_companyrisksummary_presenteeism_risk_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyrisksummary",
            name="presenteeism_recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="presenteeism_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("veryhigh", "Very High"),
                ],
                default="low",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="stress_and_wellbeing_recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="stress_and_wellbeing_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("veryhigh", "Very High"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="wider_risks_recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="wider_risks_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("veryhigh", "Very High"),
                ],
                default="low",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="workplace_stress_recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyrisksummary",
            name="workplace_stress_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("veryhigh", "Very High"),
                ],
                default="low",
                max_length=10,
                null=True,
            ),
        ),
    ]
