# Generated by Django 5.1.3 on 2025-05-02 14:55

from django.db import migrations
from django.contrib.auth import get_user_model


def lowercase_emails(apps, schema_editor):
  User = get_user_model()

  for user in User.objects.all():
    if user.email != user.email.lower():
      user.email = user.email.lower()
      user.save(update_fields=["email"])


class Migration(migrations.Migration):

  dependencies = [
      (
          "bessie",
          "0014_alter_companyrisksummary_presenteeism_recommendations_and_more",
      ),
      ("users", "0002_user_user_type_alter_user_groups"),
  ]

  operations = [
      migrations.RunPython(
        lowercase_emails, reverse_code=migrations.RunPython.noop),
  ]
