# Generated by Django 5.1.3 on 2025-05-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("bessie", "0015_1_cleanup_duplicate_companyadmin"),
	]

	operations = [
		migrations.CreateModel(
			name="EmployeeProcessTask",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("job_id", models.IntegerField()),
				("chunks_number", models.IntegerField()),
				("chunks_completed", models.IntegerField(default=0)),
				("notification_email", models.EmailField(max_length=254)),
				("completed", models.BooleanField(default=False)),
				(
					"company",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to="bessie.company"
					),
				),
			],
		),
	]
