# Generated by Django 5.1.3 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ("bessie", "0016_employeeprocesstask"),
  ]

  operations = [
    migrations.AddField(
      model_name="employee",
      name="magic_link_expiry",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name="employee",
      name="magic_link_token",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
    migrations.AddField(
      model_name="employee",
      name="unique_id",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
  ]
