# Generated by Django 5.1.3 on 2025-07-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bessie_admin',
            field=models.BooleanField(default=False),
        ),
    ]
