# Generated by Django 5.1.3 on 2025-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_orgquiztakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgquiztakers',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
