# Generated by Django 5.1.3 on 2025-03-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_orgquiztakers_consent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgquiztakers',
            options={'ordering': ['-first_name'], 'verbose_name': 'Quiz Taker', 'verbose_name_plural': 'Quiz Takers'},
        ),
    ]
