# Generated by Django 5.1.3 on 2025-07-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_orgquiztakers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgquiztakers',
            name='future_planning',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='impact_assessment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='leadership_app',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='org_polices',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='performance_management',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='proceed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='training_and_dev',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='workplace_culture',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='workplace_env',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orgquiztakers',
            name='consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
