# Generated by Django 5.1.3 on 2025-06-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_orgquiztakers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgquiztakers',
            name='org',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='position',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='proceed',
            field=models.BooleanField(default=False),
        ),
    ]
