# Generated by Django 5.1.3 on 2025-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_orgquiztakers_org_orgquiztakers_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgquiztakers',
            name='future_planning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='impact_assessment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='leadership_app',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='org_polices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='performance_management',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='training_and_dev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='workplace_culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgquiztakers',
            name='workplace_env',
            field=models.IntegerField(default=0),
        ),
    ]
